### ISSUE TITLE
compare with local/remote master.

### ISSUE THREAD

**Issue by aladdin-add** [not-an-aardvark/git-delete-squashed#3]
currently it seems compare with local master, but maybe there is some difference between local/remote master.

**Comment by not-an-aardvark** [comment]
Hmm, I'm not sure this should be changed -- it seems more intuitive for it to just compare with the local branch. The developer can always use `git pull` to sync the branches.

**Comment by not-an-aardvark** [comment]
Closing because I think the current behavior is better.
